apiVersion: v1
kind: Pod
metadata:
  name: dangling-http
spec:
  containers:
  - name: dangling-http
    image: bryanlatten/docker-dangling-http
    ports:
    - containerPort: 3000
    livenessProbe:
      httpGet:
        path: /
        port: 3000
      initialDelaySeconds: 10
      periodSeconds: 5
